/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_powerapi_jjoules_jni_Perf */

#ifndef _Included_org_powerapi_jjoules_jni_Perf
#define _Included_org_powerapi_jjoules_jni_Perf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_powerapi_jjoules_jni_Perf
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_powerapi_jjoules_jni_Perf_start
  (JNIEnv *, jobject);

/*
 * Class:     org_powerapi_jjoules_jni_Perf
 * Method:    stop
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_powerapi_jjoules_jni_Perf_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
